### ISSUE TITLE
未来发展讨论的Google Link

### ISSUE THREAD

**Issue by Ronten-Yang** [ECUST-Leap/ecust-leap.github.io#267] opened 2023-02-24 01:56 UTC
https://docs.google.com/document/d/1K4rHupeMqVRVgvd3i2ePUA57LM6Qnkhq_nb5vz5hZGg/edit?usp=sharing

**Comment by Yuchen-Wang-SH** [comment] 2023-02-24 02:07
duplicate of #265

**Closed by Yuchen-Wang-SH** 2023-02-24 02:07 UTC
Labels: duplicate
